export const MOCK_APPOINTMENTS = [
  {
    id: 'appt1',
    clientId: '1',
    title: 'Therapy Session',
    startTime: '2023-04-26T15:30:00',
    endTime: '2023-04-26T16:30:00',
    status: 'completed',
    type: 'individual',
    notes: 'Discussed anxiety triggers and coping mechanisms',
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office A',
    billable: true,
    billingStatus: 'billed',
    cancellationReason: null,
    attended: true,
    insuranceBilled: true,
    insuranceResponse: 'approved',
    paymentAmount: 25.00,
    totalCharge: 125.00
  },
  {
    id: 'appt2',
    clientId: '1',
    title: 'Therapy Session',
    startTime: '2023-05-10T14:00:00',
    endTime: '2023-05-10T15:00:00',
    status: 'scheduled',
    type: 'individual',
    notes: null,
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office A',
    billable: true,
    billingStatus: 'not-billed',
    cancellationReason: null,
    attended: null,
    insuranceBilled: false,
    insuranceResponse: null,
    paymentAmount: null,
    totalCharge: 125.00
  },
  {
    id: 'appt3',
    clientId: '1',
    title: 'Initial Consultation',
    startTime: '2023-03-15T10:00:00',
    endTime: '2023-03-15T11:00:00',
    status: 'completed',
    type: 'initial-consultation',
    notes: 'First session. Client discussed history of anxiety and depression.',
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office B',
    billable: true,
    billingStatus: 'billed',
    cancellationReason: null,
    attended: true,
    insuranceBilled: true,
    insuranceResponse: 'approved',
    paymentAmount: 25.00,
    totalCharge: 150.00
  },
  {
    id: 'appt4',
    clientId: '1',
    title: 'Therapy Session',
    startTime: '2023-04-05T14:00:00',
    endTime: '2023-04-05T15:00:00',
    status: 'canceled',
    type: 'individual',
    notes: 'Client canceled due to illness',
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office A',
    billable: false,
    billingStatus: 'not-billable',
    cancellationReason: 'client-sick',
    attended: false,
    insuranceBilled: false,
    insuranceResponse: null,
    paymentAmount: 0,
    totalCharge: 0
  },
  {
    id: 'appt5',
    clientId: '1',
    title: 'Medication Review',
    startTime: '2023-04-12T11:00:00',
    endTime: '2023-04-12T11:30:00',
    status: 'completed',
    type: 'medication-review',
    notes: 'Reviewed current medications. Adjusted dosage for anxiety medication.',
    therapistId: 'therapist3',
    therapistName: 'Dr. Johnson',
    location: 'Office C',
    billable: true,
    billingStatus: 'billed',
    cancellationReason: null,
    attended: true,
    insuranceBilled: true,
    insuranceResponse: 'approved',
    paymentAmount: 15.00,
    totalCharge: 75.00
  },
  {
    id: 'appt6',
    clientId: '1',
    title: 'Therapy Session',
    startTime: '2023-05-24T14:00:00',
    endTime: '2023-05-24T15:00:00',
    status: 'scheduled',
    type: 'individual',
    notes: null,
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office A',
    billable: true,
    billingStatus: 'not-billed',
    cancellationReason: null,
    attended: null,
    insuranceBilled: false,
    insuranceResponse: null,
    paymentAmount: null,
    totalCharge: 125.00
  },
  {
    id: 'appt7',
    clientId: '2',
    title: 'Family Therapy Session',
    startTime: '2023-05-12T10:30:00',
    endTime: '2023-05-12T12:00:00',
    status: 'scheduled',
    type: 'family',
    notes: null,
    therapistId: 'therapist2',
    therapistName: 'Dr. Jones',
    location: 'Office D',
    billable: true,
    billingStatus: 'not-billed',
    cancellationReason: null,
    attended: null,
    insuranceBilled: false,
    insuranceResponse: null,
    paymentAmount: null,
    totalCharge: 175.00
  },
  {
    id: 'appt8',
    clientId: '3',
    title: 'Therapy Session',
    startTime: '2023-03-05T14:00:00',
    endTime: '2023-03-05T15:00:00',
    status: 'completed',
    type: 'individual',
    notes: 'Discussed anger management techniques. Client seems resistant to change.',
    therapistId: 'therapist1',
    therapistName: 'Dr. Smith',
    location: 'Office A',
    billable: true,
    billingStatus: 'billed',
    cancellationReason: null,
    attended: true,
    insuranceBilled: true,
    insuranceResponse: 'approved',
    paymentAmount: 25.00,
    totalCharge: 125.00
  }
]; 