export const MOCK_CLIENTS = [
  { 
    id: '1', 
    firstName: 'John', 
    lastName: 'Doe', 
    email: 'john.doe@example.com', 
    phone: '(555) 123-4567', 
    status: 'active',
    dateOfBirth: '1985-06-15',
    nextAppointment: '2023-05-10T14:00:00',
    primaryTherapistName: 'Dr. Smith',
    tags: ['Anxiety', 'Depression'],
    alerts: [
      { type: 'warning', message: 'Insurance expiring in 30 days' }
    ],
    insuranceProvider: 'Blue Cross Blue Shield',
    lastAppointment: '2023-04-26T15:30:00',
    unpaidBalance: 250.00,
    gender: 'male',
    maritalStatus: 'married',
    address: {
      street: '123 Main St',
      unit: 'Apt 4B',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704',
      country: 'United States'
    },
    emergencyContact: {
      firstName: 'Jane',
      lastName: 'Doe',
      relationship: 'spouse',
      phone: '(555) 987-6543',
      email: 'jane.doe@example.com'
    },
    insuranceDetails: {
      primary: {
        provider: 'Blue Cross Blue Shield',
        planName: 'PPO Choice Plus',
        memberId: 'XYZ123456789',
        groupNumber: 'GRP78901234',
        policyHolder: {
          isSelf: true,
          firstName: 'John',
          lastName: 'Doe',
          dateOfBirth: '1985-06-15',
          relationship: 'self'
        },
        coverageStartDate: '2023-01-01',
        coverageEndDate: '2023-12-31',
        copay: 25,
        coinsurance: 20,
        deductible: 500,
        deductibleMet: 350,
        outOfPocketMax: 3000,
        outOfPocketMet: 1200,
        authorizationRequired: true,
        authorizationNumber: 'AUTH123456',
        authorizationStartDate: '2023-02-15',
        authorizationEndDate: '2023-08-15',
        sessionsApproved: 20,
        sessionsUsed: 12
      },
      secondary: {
        provider: 'Aetna',
        planName: 'HMO Basic',
        memberId: 'AET987654321',
        groupNumber: 'GRP54321678',
        policyHolder: {
          isSelf: false,
          firstName: 'Jane',
          lastName: 'Doe',
          dateOfBirth: '1986-08-20',
          relationship: 'spouse'
        },
        coverageStartDate: '2023-01-01',
        coverageEndDate: '2023-12-31',
        copay: 35,
        coinsurance: 30,
        deductible: 1000,
        deductibleMet: 200,
        outOfPocketMax: 4000,
        outOfPocketMet: 500
      }
    },
    employmentStatus: 'Full-time',
    employer: 'ABC Company',
    occupation: 'Software Engineer',
    referralSource: 'Doctor Referral',
    preferredContactMethod: ['email', 'phone'],
    contactNotes: 'Prefers afternoon calls',
    preferredPronoun: 'he/him',
    preferredName: 'Johnny',
    primaryLanguage: 'English',
    secondaryLanguage: 'Spanish',
    ethnicity: 'Hispanic/Latino',
    race: 'White',
    religiousPreference: 'Catholic',
    primaryCareProvider: {
      name: 'Dr. Jennifer Wilson',
      facility: 'Springfield Medical Center',
      phone: '(555) 111-2222',
      email: 'jwilson@springfieldmedical.com',
      address: '789 Health St, Springfield, IL 62704',
      lastVisit: '2023-02-10'
    }
  },
  { 
    id: '2', 
    firstName: 'Jane', 
    lastName: 'Smith', 
    email: 'jane.smith@example.com', 
    phone: '(555) 987-6543', 
    status: 'onboarding',
    dateOfBirth: '1990-03-22',
    nextAppointment: '2023-05-12T10:30:00',
    primaryTherapistName: 'Dr. Jones',
    tags: ['Family Therapy', 'Grief'],
    alerts: [],
    insuranceProvider: 'Aetna',
    lastAppointment: null,
    unpaidBalance: 0,
    gender: 'female',
    maritalStatus: 'single',
    address: {
      street: '456 Oak Ave',
      unit: '',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62701',
      country: 'United States'
    }
  },
  { 
    id: '3', 
    firstName: 'Robert', 
    lastName: 'Johnson', 
    email: 'robert.j@example.com', 
    phone: '(555) 567-8901', 
    status: 'inactive',
    dateOfBirth: '1978-11-30',
    nextAppointment: null,
    primaryTherapistName: 'Dr. Smith',
    tags: ['Substance Abuse', 'Anger Management'],
    alerts: [
      { type: 'error', message: 'No appointment in 60+ days' }
    ],
    insuranceProvider: 'UnitedHealthcare',
    lastAppointment: '2023-03-05T14:00:00',
    unpaidBalance: 75.00,
    gender: 'male',
    maritalStatus: 'divorced'
  },
  { 
    id: '4', 
    firstName: 'Emily', 
    lastName: 'Williams', 
    email: 'emily.w@example.com', 
    phone: '(555) 234-5678', 
    status: 'active',
    dateOfBirth: '1992-08-17',
    nextAppointment: '2023-05-15T16:15:00',
    primaryTherapistName: 'Dr. Brown',
    tags: ['PTSD', 'Anxiety'],
    alerts: [],
    insuranceProvider: 'Cigna',
    lastAppointment: '2023-04-24T16:15:00',
    unpaidBalance: 0,
    gender: 'female',
    maritalStatus: 'married'
  },
  { 
    id: '5', 
    firstName: 'Michael', 
    lastName: 'Brown', 
    email: 'michael.b@example.com', 
    phone: '(555) 876-5432', 
    status: 'discharged',
    dateOfBirth: '1982-04-09',
    nextAppointment: null,
    primaryTherapistName: 'Dr. Jones',
    tags: ['Depression'],
    alerts: [],
    insuranceProvider: 'Medicare',
    lastAppointment: '2023-04-10T11:00:00',
    unpaidBalance: 0,
    gender: 'male',
    maritalStatus: 'single'
  },
  { 
    id: '6', 
    firstName: 'Sarah', 
    lastName: 'Miller', 
    email: 'sarah.m@example.com', 
    phone: '(555) 345-6789', 
    status: 'active',
    dateOfBirth: '1988-12-05',
    nextAppointment: '2023-05-18T09:30:00',
    primaryTherapistName: 'Dr. Wilson',
    tags: ['Relationship Issues', 'Self-Esteem'],
    alerts: [],
    insuranceProvider: 'Aetna',
    lastAppointment: '2023-04-27T09:30:00',
    unpaidBalance: 25.00,
    gender: 'female',
    maritalStatus: 'single'
  },
  { 
    id: '7', 
    firstName: 'David', 
    lastName: 'Garcia', 
    email: 'david.g@example.com', 
    phone: '(555) 789-0123', 
    status: 'on-hold',
    dateOfBirth: '1975-07-22',
    nextAppointment: null,
    primaryTherapistName: 'Dr. Smith',
    tags: ['Bipolar Disorder', 'Medication Management'],
    alerts: [
      { type: 'warning', message: 'Payment past due' }
    ],
    insuranceProvider: 'UnitedHealthcare',
    lastAppointment: '2023-04-15T13:45:00',
    unpaidBalance: 150.00,
    gender: 'male',
    maritalStatus: 'married'
  },
  { 
    id: '8', 
    firstName: 'Lisa', 
    lastName: 'Martinez', 
    email: 'lisa.m@example.com', 
    phone: '(555) 456-7890', 
    status: 'active',
    dateOfBirth: '1993-05-30',
    nextAppointment: '2023-05-20T14:00:00',
    primaryTherapistName: 'Dr. Brown',
    tags: ['Eating Disorder', 'Anxiety'],
    alerts: [],
    insuranceProvider: 'Cigna',
    lastAppointment: '2023-04-29T14:00:00',
    unpaidBalance: 0,
    gender: 'female',
    maritalStatus: 'single'
  },
  { 
    id: '9', 
    firstName: 'James', 
    lastName: 'Wilson', 
    email: 'james.w@example.com', 
    phone: '(555) 678-9012', 
    status: 'onboarding',
    dateOfBirth: '1980-02-14',
    nextAppointment: '2023-05-11T11:00:00',
    primaryTherapistName: 'Dr. Johnson',
    tags: ['Work Stress', 'Depression'],
    alerts: [],
    insuranceProvider: 'Blue Cross Blue Shield',
    lastAppointment: null,
    unpaidBalance: 0,
    gender: 'male',
    maritalStatus: 'divorced'
  },
  { 
    id: '10', 
    firstName: 'Jennifer', 
    lastName: 'Anderson', 
    email: 'jennifer.a@example.com', 
    phone: '(555) 890-1234', 
    status: 'active',
    dateOfBirth: '1986-09-20',
    nextAppointment: '2023-05-19T15:30:00',
    primaryTherapistName: 'Dr. Wilson',
    tags: ['Trauma', 'PTSD'],
    alerts: [],
    insuranceProvider: 'Medicaid',
    lastAppointment: '2023-04-28T15:30:00',
    unpaidBalance: 50.00,
    gender: 'female',
    maritalStatus: 'widowed'
  }
]; 