export const MOCK_DOCUMENTS = [
  {
    id: 'doc1',
    clientId: '1',
    name: 'Intake Form.pdf',
    type: 'intake',
    uploadDate: '2023-03-15T11:30:00',
    uploadedBy: 'Dr. Smith',
    size: 1245000, // in bytes
    status: 'signed',
    signedBy: 'John Doe',
    signedDate: '2023-03-15T11:45:00',
    category: 'intake',
    description: 'Initial client intake form',
    tags: ['intake', 'initial', 'forms'],
    url: '/documents/intake_form_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'staff-only'
  },
  {
    id: 'doc2',
    clientId: '1',
    name: 'Consent for Treatment.pdf',
    type: 'consent',
    uploadDate: '2023-03-15T11:35:00',
    uploadedBy: 'Dr. Smith',
    size: 982000, // in bytes
    status: 'signed',
    signedBy: 'John Doe',
    signedDate: '2023-03-15T11:50:00',
    category: 'legal',
    description: 'Consent for mental health treatment',
    tags: ['consent', 'legal', 'required'],
    url: '/documents/consent_treatment_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'staff-only'
  },
  {
    id: 'doc3',
    clientId: '1',
    name: 'HIPAA Privacy Notice.pdf',
    type: 'hipaa',
    uploadDate: '2023-03-15T11:40:00',
    uploadedBy: 'Dr. Smith',
    size: 1562000, // in bytes
    status: 'signed',
    signedBy: 'John Doe',
    signedDate: '2023-03-15T11:55:00',
    category: 'legal',
    description: 'HIPAA privacy policy acknowledgment',
    tags: ['hipaa', 'privacy', 'legal', 'required'],
    url: '/documents/hipaa_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'staff-only'
  },
  {
    id: 'doc4',
    clientId: '1',
    name: 'Insurance Card - Front.jpg',
    type: 'insurance',
    uploadDate: '2023-03-15T12:00:00',
    uploadedBy: 'Administrative Staff',
    size: 456000, // in bytes
    status: 'verified',
    signedBy: null,
    signedDate: null,
    category: 'insurance',
    description: 'Front of client insurance card',
    tags: ['insurance', 'documentation'],
    url: '/documents/insurance_front_john_doe.jpg',
    thumbnailUrl: '/thumbnails/jpg_thumbnail.png',
    accessLevel: 'admin-only'
  },
  {
    id: 'doc5',
    clientId: '1',
    name: 'Insurance Card - Back.jpg',
    type: 'insurance',
    uploadDate: '2023-03-15T12:01:00',
    uploadedBy: 'Administrative Staff',
    size: 432000, // in bytes
    status: 'verified',
    signedBy: null,
    signedDate: null,
    category: 'insurance',
    description: 'Back of client insurance card',
    tags: ['insurance', 'documentation'],
    url: '/documents/insurance_back_john_doe.jpg',
    thumbnailUrl: '/thumbnails/jpg_thumbnail.png',
    accessLevel: 'admin-only'
  },
  {
    id: 'doc6',
    clientId: '1',
    name: 'Previous Treatment Records.pdf',
    type: 'medical',
    uploadDate: '2023-03-20T14:30:00',
    uploadedBy: 'John Doe',
    size: 2450000, // in bytes
    status: 'verified',
    signedBy: null,
    signedDate: null,
    category: 'medical',
    description: 'Records from previous therapist',
    tags: ['medical', 'history', 'external'],
    url: '/documents/previous_records_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'provider-only'
  },
  {
    id: 'doc7',
    clientId: '1',
    name: 'Treatment Plan.pdf',
    type: 'treatment',
    uploadDate: '2023-04-05T16:00:00',
    uploadedBy: 'Dr. Smith',
    size: 768000, // in bytes
    status: 'signed',
    signedBy: 'John Doe',
    signedDate: '2023-04-05T16:30:00',
    category: 'clinical',
    description: 'Initial treatment plan',
    tags: ['treatment', 'plan', 'clinical'],
    url: '/documents/treatment_plan_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'provider-only'
  },
  {
    id: 'doc8',
    clientId: '1',
    name: 'Anxiety Assessment.pdf',
    type: 'assessment',
    uploadDate: '2023-04-12T11:45:00',
    uploadedBy: 'Dr. Smith',
    size: 532000, // in bytes
    status: 'completed',
    signedBy: null,
    signedDate: null,
    category: 'assessment',
    description: 'Standardized anxiety assessment results',
    tags: ['assessment', 'anxiety', 'clinical'],
    url: '/documents/anxiety_assessment_john_doe.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'provider-only'
  },
  {
    id: 'doc9',
    clientId: '2',
    name: 'Intake Form.pdf',
    type: 'intake',
    uploadDate: '2023-04-10T09:30:00',
    uploadedBy: 'Dr. Jones',
    size: 1145000, // in bytes
    status: 'signed',
    signedBy: 'Jane Smith',
    signedDate: '2023-04-10T09:45:00',
    category: 'intake',
    description: 'Initial client intake form',
    tags: ['intake', 'initial', 'forms'],
    url: '/documents/intake_form_jane_smith.pdf',
    thumbnailUrl: '/thumbnails/pdf_thumbnail.png',
    accessLevel: 'staff-only'
  }
]; 