-- Staff table
CREATE TABLE IF NOT EXISTS staff (
  id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  last_name TEXT NOT NULL,
  suffix TEXT,
  type_of_clinician TEXT,
  npi_number TEXT,
  supervisor_id INTEGER REFERENCES staff(id),
  role TEXT NOT NULL,
  roles TEXT[],
  email TEXT NOT NULL,
  phone TEXT,
  can_receive_texts BOOLEAN DEFAULT FALSE,
  work_phone TEXT,
  home_phone TEXT,
  address TEXT,
  city_state TEXT,
  zip_code TEXT,
  license_state TEXT,
  license_type TEXT,
  license_number TEXT,
  license_expiration TIMESTAMP,
  formal_name TEXT,
  professional_title TEXT,
  languages TEXT[],
  status TEXT DEFAULT 'active' NOT NULL,
  profile_image TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
); 